// <auto-generated />
using System;
using ControleTiAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ControleTiAPI.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20230414125906_ServerSchema")]
    partial class ServerSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("ti")
                .HasAnnotation("ProductVersion", "7.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ControleTiAPI.Models.CellPhone", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<int>("memorySize")
                        .HasColumnType("int");

                    b.Property<string>("model")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("operationalSystem")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("processingUnit")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("storageSize")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.ToTable("cellPhone", "ti");
                });

            modelBuilder.Entity("ControleTiAPI.Models.Chip", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("account")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("acctualICCID")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("acquisitionDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("assetNumber")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("cellphoneId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("createdAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getdate()");

                    b.Property<int?>("departmentId")
                        .HasColumnType("int");

                    b.Property<int?>("employeeId")
                        .HasColumnType("int");

                    b.Property<string>("notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("number")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("status")
                        .HasColumnType("int");

                    b.Property<string>("type")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("updatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getdate()");

                    b.HasKey("id");

                    b.HasIndex("cellphoneId");

                    b.HasIndex("departmentId");

                    b.HasIndex("employeeId");

                    b.HasIndex("number")
                        .IsUnique()
                        .HasDatabaseName("ChipNumberIndex");

                    b.ToTable("chip", "ti");
                });

            modelBuilder.Entity("ControleTiAPI.Models.Computer", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<DateTime?>("acquisitionDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("assetNumber")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("code")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("computerType")
                        .HasColumnType("int");

                    b.Property<DateTime?>("createdAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getdate()");

                    b.Property<int?>("departmentId")
                        .HasColumnType("int");

                    b.Property<int?>("employeeId")
                        .HasColumnType("int");

                    b.Property<bool>("isGood")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("lastPreventiveDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("memorySize")
                        .HasColumnType("int");

                    b.Property<string>("notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("operationalSystem")
                        .IsRequired()
                        .HasMaxLength(75)
                        .HasColumnType("nvarchar(75)");

                    b.Property<int>("processorId")
                        .HasColumnType("int");

                    b.Property<int>("profileId")
                        .HasColumnType("int");

                    b.Property<int>("rankOperationalSystem")
                        .HasColumnType("int");

                    b.Property<int>("status")
                        .HasColumnType("int");

                    b.Property<int>("storageId")
                        .HasColumnType("int");

                    b.Property<string>("ticketId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("id");

                    b.HasIndex("code")
                        .IsUnique()
                        .HasDatabaseName("CodeComputerIndex");

                    b.HasIndex("departmentId");

                    b.HasIndex("employeeId");

                    b.HasIndex("processorId");

                    b.HasIndex("profileId");

                    b.HasIndex("storageId");

                    b.ToTable("computer", "ti");
                });

            modelBuilder.Entity("ControleTiAPI.Models.ComputerLog", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("code")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("computerId")
                        .HasColumnType("int");

                    b.Property<string>("computerProfile")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("department")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("employee")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("enterprise")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("isGood")
                        .HasColumnType("bit");

                    b.Property<int>("memorySize")
                        .HasColumnType("int");

                    b.Property<string>("operationalSystem")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("processingUnit")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("status")
                        .HasColumnType("int");

                    b.Property<int>("storageSize")
                        .HasColumnType("int");

                    b.Property<string>("storageType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("updatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getdate()");

                    b.HasKey("id");

                    b.HasIndex("computerId");

                    b.ToTable("computerLog", "ti");
                });

            modelBuilder.Entity("ControleTiAPI.Models.ComputerMemory", b =>
                {
                    b.Property<int>("memoryId")
                        .HasColumnType("int");

                    b.Property<int>("computerId")
                        .HasColumnType("int");

                    b.Property<int>("qtde")
                        .HasColumnType("int");

                    b.HasKey("memoryId", "computerId");

                    b.HasIndex("computerId");

                    b.ToTable("computerMemory", "ti");
                });

            modelBuilder.Entity("ControleTiAPI.Models.ComputerProfile", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<int>("memoryMinSize")
                        .HasColumnType("int");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasMaxLength(75)
                        .HasColumnType("nvarchar(75)");

                    b.Property<int>("rankOfOperationSystem")
                        .HasColumnType("int");

                    b.Property<int>("rankOfProcessingUnit")
                        .HasColumnType("int");

                    b.Property<int>("storageMinSize")
                        .HasColumnType("int");

                    b.Property<string>("storageType")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.HasKey("id");

                    b.HasIndex("name")
                        .IsUnique()
                        .HasDatabaseName("NameProfileIndex");

                    b.ToTable("profile", "ti");
                });

            modelBuilder.Entity("ControleTiAPI.Models.ComputersReport", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<int>("countComputerIsGood")
                        .HasColumnType("int");

                    b.Property<int>("countComputerIsNotGood")
                        .HasColumnType("int");

                    b.Property<DateTime>("reportDate")
                        .HasColumnType("datetime2");

                    b.HasKey("id");

                    b.ToTable("computerReport", "ti");
                });

            modelBuilder.Entity("ControleTiAPI.Models.DVR", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<DateTime?>("acquisitionDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("activeCams")
                        .HasColumnType("int");

                    b.Property<string>("assetNumber")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("brand")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("code")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("createdAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("dvrIP")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("dvrPassword")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("dvrPort")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("dvrUser")
                        .IsRequired()
                        .HasMaxLength(75)
                        .HasColumnType("nvarchar(75)");

                    b.Property<bool>("hasBalun")
                        .HasColumnType("bit");

                    b.Property<double>("hdSize")
                        .HasColumnType("float");

                    b.Property<DateTime?>("lastPreventive")
                        .HasColumnType("datetime2");

                    b.Property<string>("location")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("model")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("qtdeChannels")
                        .HasColumnType("int");

                    b.Property<int>("status")
                        .HasColumnType("int");

                    b.Property<string>("ticketId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("updatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("id");

                    b.HasIndex("code")
                        .IsUnique()
                        .HasDatabaseName("CodeDVRIndex");

                    b.ToTable("dvr", "ti");
                });

            modelBuilder.Entity("ControleTiAPI.Models.Department", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<DateTime?>("createdAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("description")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("enterprise")
                        .IsRequired()
                        .HasMaxLength(75)
                        .HasColumnType("nvarchar(75)");

                    b.Property<DateTime?>("updatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("id");

                    b.ToTable("department", "ti");
                });

            modelBuilder.Entity("ControleTiAPI.Models.Employee", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("alternativeEmail")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("alternativeEmailPassword")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("createdAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("departmentId")
                        .HasColumnType("int");

                    b.Property<string>("displayName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("emailPassword")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("ingressDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("status")
                        .HasColumnType("int");

                    b.Property<DateTime?>("updatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("id");

                    b.HasIndex("departmentId");

                    b.HasIndex("name")
                        .IsUnique()
                        .HasDatabaseName("UserNameEmployee");

                    b.ToTable("employee", "ti");
                });

            modelBuilder.Entity("ControleTiAPI.Models.Memory", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<int>("memoryPentSize")
                        .HasColumnType("int");

                    b.Property<string>("model")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("id");

                    b.ToTable("memory", "ti");
                });

            modelBuilder.Entity("ControleTiAPI.Models.NetworkNode", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("code")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("createdAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("employeeId")
                        .HasColumnType("int");

                    b.Property<string>("location")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("patchPanelLocation")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("patchPanelNodeId")
                        .HasMaxLength(75)
                        .HasColumnType("nvarchar(75)");

                    b.Property<int?>("patchPanelPort")
                        .HasColumnType("int");

                    b.Property<int>("switchId")
                        .HasColumnType("int");

                    b.Property<int>("switchPort")
                        .HasColumnType("int");

                    b.Property<DateTime?>("updatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("id");

                    b.HasIndex("code")
                        .IsUnique()
                        .HasDatabaseName("CodeNetworkNodeIndex");

                    b.HasIndex("employeeId");

                    b.HasIndex("switchId");

                    b.ToTable("networkNode", "ti");
                });

            modelBuilder.Entity("ControleTiAPI.Models.Nobreak", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<DateTime?>("acquisitionDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("assetNumber")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("brand")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("code")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("createdAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("isSenoidal")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("lastPreventive")
                        .HasColumnType("datetime2");

                    b.Property<string>("location")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("model")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("qtdeVA")
                        .HasColumnType("int");

                    b.Property<int>("status")
                        .HasColumnType("int");

                    b.Property<string>("ticketId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("typeOfUse")
                        .HasColumnType("int");

                    b.Property<DateTime?>("updatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("id");

                    b.HasIndex("code")
                        .IsUnique()
                        .HasDatabaseName("CodeNobreakIndex");

                    b.ToTable("nobreak", "ti");
                });

            modelBuilder.Entity("ControleTiAPI.Models.Preventives.ComputerPreventive", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<int>("computerId")
                        .HasColumnType("int");

                    b.Property<DateTime>("preventiveDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ticketId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("id");

                    b.HasIndex("computerId");

                    b.ToTable("computerPreventive", "ti");
                });

            modelBuilder.Entity("ControleTiAPI.Models.Preventives.DVRPreventive", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<int>("dvrId")
                        .HasColumnType("int");

                    b.Property<DateTime>("preventiveDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ticketId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("id");

                    b.HasIndex("dvrId");

                    b.ToTable("dvrPreventive", "ti");
                });

            modelBuilder.Entity("ControleTiAPI.Models.Preventives.NobreakPreventive", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<int>("nobreakId")
                        .HasColumnType("int");

                    b.Property<DateTime>("preventiveDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ticketId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("id");

                    b.HasIndex("nobreakId");

                    b.ToTable("nobreakPreventive", "ti");
                });

            modelBuilder.Entity("ControleTiAPI.Models.Preventives.ServerPreventive", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<int>("hostId")
                        .HasColumnType("int");

                    b.Property<DateTime>("preventiveDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ticketId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("id");

                    b.HasIndex("hostId");

                    b.ToTable("serverPreventive", "ti");
                });

            modelBuilder.Entity("ControleTiAPI.Models.Printer", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<DateTime?>("acquisitionDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("assetNumber")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("brand")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("code")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("createdAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("location")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("model")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("printerIP")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("printerPassword")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("printerUser")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("serialNumber")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("status")
                        .HasColumnType("int");

                    b.Property<string>("supplies")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("type")
                        .HasColumnType("int");

                    b.Property<DateTime?>("updatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("id");

                    b.HasIndex("code")
                        .IsUnique()
                        .HasDatabaseName("PrinterCodeUniqueIndex");

                    b.ToTable("printer", "ti");
                });

            modelBuilder.Entity("ControleTiAPI.Models.ProcessingUnit", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("frequency")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("generation")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("model")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("rankProcessingUnit")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.ToTable("processingUnit", "ti");
                });

            modelBuilder.Entity("ControleTiAPI.Models.Ramal", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<DateTime?>("acquisitionDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("assetNumber")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("createdAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getdate()");

                    b.Property<int>("departmentId")
                        .HasColumnType("int");

                    b.Property<string>("deviceConfig")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("deviceIP")
                        .IsRequired()
                        .HasMaxLength(75)
                        .HasColumnType("nvarchar(75)");

                    b.Property<string>("devicePassword")
                        .IsRequired()
                        .HasMaxLength(75)
                        .HasColumnType("nvarchar(75)");

                    b.Property<string>("deviceUser")
                        .IsRequired()
                        .HasMaxLength(75)
                        .HasColumnType("nvarchar(75)");

                    b.Property<int?>("employeeId")
                        .HasColumnType("int");

                    b.Property<string>("exitNumber")
                        .IsRequired()
                        .HasMaxLength(75)
                        .HasColumnType("nvarchar(75)");

                    b.Property<bool>("isDepartment")
                        .HasColumnType("bit");

                    b.Property<string>("model")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("number")
                        .IsRequired()
                        .HasMaxLength(75)
                        .HasColumnType("nvarchar(75)");

                    b.Property<int>("status")
                        .HasColumnType("int");

                    b.Property<DateTime?>("updatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getdate()");

                    b.HasKey("id");

                    b.HasIndex("departmentId");

                    b.HasIndex("employeeId");

                    b.HasIndex("number")
                        .IsUnique()
                        .HasDatabaseName("RamalNumberIndex");

                    b.ToTable("ramal", "ti");
                });

            modelBuilder.Entity("ControleTiAPI.Models.Router", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<DateTime?>("acquisitionDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("assetNumber")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("brand")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("code")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("createdAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("location")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("routerIP")
                        .IsRequired()
                        .HasMaxLength(75)
                        .HasColumnType("nvarchar(75)");

                    b.Property<string>("routerMAC")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("routerPassword")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("routerSSID")
                        .IsRequired()
                        .HasMaxLength(75)
                        .HasColumnType("nvarchar(75)");

                    b.Property<string>("routerUser")
                        .IsRequired()
                        .HasMaxLength(75)
                        .HasColumnType("nvarchar(75)");

                    b.Property<int>("status")
                        .HasColumnType("int");

                    b.Property<DateTime?>("updatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("id");

                    b.HasIndex("code")
                        .IsUnique()
                        .HasDatabaseName("CodeRouterIndex");

                    b.ToTable("router", "ti");
                });

            modelBuilder.Entity("ControleTiAPI.Models.ServerFunctionality", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("description")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("id");

                    b.ToTable("serverFunctionality", "ti");
                });

            modelBuilder.Entity("ControleTiAPI.Models.ServerHost", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<DateTime?>("acquisitionDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("assetNumber")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("code")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("lastPreventiveDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("machineBrand")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("machineModel")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("operationalSystemDescription")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("processorFrequency")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("processorModelDescription")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("status")
                        .HasColumnType("int");

                    b.Property<string>("ticketId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.HasIndex("code")
                        .IsUnique()
                        .HasDatabaseName("CodeSrvHostIndex");

                    b.ToTable("serverHost", "ti");
                });

            modelBuilder.Entity("ControleTiAPI.Models.ServerMemory", b =>
                {
                    b.Property<int>("memoryId")
                        .HasColumnType("int");

                    b.Property<int>("serverHostId")
                        .HasColumnType("int");

                    b.Property<int>("qtde")
                        .HasColumnType("int");

                    b.HasKey("memoryId", "serverHostId");

                    b.HasIndex("serverHostId");

                    b.ToTable("serverMemory", "ti");
                });

            modelBuilder.Entity("ControleTiAPI.Models.ServerStorage", b =>
                {
                    b.Property<int>("storageId")
                        .HasColumnType("int");

                    b.Property<int>("serverHostId")
                        .HasColumnType("int");

                    b.Property<int>("qtde")
                        .HasColumnType("int");

                    b.HasKey("storageId", "serverHostId");

                    b.HasIndex("serverHostId");

                    b.ToTable("serverStorage", "ti");
                });

            modelBuilder.Entity("ControleTiAPI.Models.ServerVM", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("code")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("memorySize")
                        .HasColumnType("int");

                    b.Property<string>("operationalSystem")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("serverHostId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("setupDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("status")
                        .HasColumnType("int");

                    b.Property<double>("storageSize")
                        .HasColumnType("float");

                    b.HasKey("id");

                    b.HasIndex("code")
                        .IsUnique()
                        .HasDatabaseName("CodeVMIndex");

                    b.HasIndex("serverHostId");

                    b.ToTable("serverVM", "ti");
                });

            modelBuilder.Entity("ControleTiAPI.Models.SkypeEmployee", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<int>("employeeId")
                        .HasColumnType("int");

                    b.Property<string>("skypePassword")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("skypeUser")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("id");

                    b.HasIndex("employeeId")
                        .IsUnique();

                    b.ToTable("skypeEmployee", "ti");
                });

            modelBuilder.Entity("ControleTiAPI.Models.Storage", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("brand")
                        .IsRequired()
                        .HasMaxLength(75)
                        .HasColumnType("nvarchar(75)");

                    b.Property<int>("storageSize")
                        .HasColumnType("int");

                    b.Property<string>("type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("id");

                    b.ToTable("storage", "ti");
                });

            modelBuilder.Entity("ControleTiAPI.Models.Switches", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<DateTime?>("acquisitionDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("assetNumber")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("brand")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("code")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("createdAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("location")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("qtdePorts")
                        .HasColumnType("int");

                    b.Property<int>("status")
                        .HasColumnType("int");

                    b.Property<string>("switchIP")
                        .IsRequired()
                        .HasMaxLength(75)
                        .HasColumnType("nvarchar(75)");

                    b.Property<string>("switchMAC")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("switchPassword")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("switchUser")
                        .IsRequired()
                        .HasMaxLength(75)
                        .HasColumnType("nvarchar(75)");

                    b.Property<DateTime?>("updatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("id");

                    b.HasIndex("code")
                        .IsUnique()
                        .HasDatabaseName("CodeSwitchIndex");

                    b.ToTable("switches", "ti");
                });

            modelBuilder.Entity("ControleTiAPI.Models.User", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("displayname")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("userIsActive")
                        .HasColumnType("bit");

                    b.Property<string>("username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("id");

                    b.HasIndex("email")
                        .IsUnique()
                        .HasDatabaseName("EmailUserIndex");

                    b.ToTable("user", "ti");
                });

            modelBuilder.Entity("ControleTiAPI.Models.UserClaims", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("claimType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("claimValue")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("userId")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("userId");

                    b.ToTable("userClaims", "ti");
                });

            modelBuilder.Entity("ControleTiAPI.Models.VpnEmployee", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<int>("employeeId")
                        .HasColumnType("int");

                    b.Property<string>("vpnPassword")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("vpnUser")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("id");

                    b.HasIndex("employeeId")
                        .IsUnique();

                    b.ToTable("vpnEmployee", "ti");
                });

            modelBuilder.Entity("ServerFunctionalityServerHost", b =>
                {
                    b.Property<int>("functionalitiesid")
                        .HasColumnType("int");

                    b.Property<int>("hostsid")
                        .HasColumnType("int");

                    b.HasKey("functionalitiesid", "hostsid");

                    b.HasIndex("hostsid");

                    b.ToTable("ServerFunctionalityServerHost", "ti");
                });

            modelBuilder.Entity("ServerFunctionalityServerVM", b =>
                {
                    b.Property<int>("functionalitiesid")
                        .HasColumnType("int");

                    b.Property<int>("virtualMachinesid")
                        .HasColumnType("int");

                    b.HasKey("functionalitiesid", "virtualMachinesid");

                    b.HasIndex("virtualMachinesid");

                    b.ToTable("ServerFunctionalityServerVM", "ti");
                });

            modelBuilder.Entity("ControleTiAPI.Models.Chip", b =>
                {
                    b.HasOne("ControleTiAPI.Models.CellPhone", "cellPhone")
                        .WithMany("chips")
                        .HasForeignKey("cellphoneId");

                    b.HasOne("ControleTiAPI.Models.Department", "department")
                        .WithMany("chips")
                        .HasForeignKey("departmentId");

                    b.HasOne("ControleTiAPI.Models.Employee", "employee")
                        .WithMany("chips")
                        .HasForeignKey("employeeId");

                    b.Navigation("cellPhone");

                    b.Navigation("department");

                    b.Navigation("employee");
                });

            modelBuilder.Entity("ControleTiAPI.Models.Computer", b =>
                {
                    b.HasOne("ControleTiAPI.Models.Department", "department")
                        .WithMany("computers")
                        .HasForeignKey("departmentId");

                    b.HasOne("ControleTiAPI.Models.Employee", "employee")
                        .WithMany("computers")
                        .HasForeignKey("employeeId");

                    b.HasOne("ControleTiAPI.Models.ProcessingUnit", "processingUnit")
                        .WithMany("computers")
                        .HasForeignKey("processorId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("ControleTiAPI.Models.ComputerProfile", "profile")
                        .WithMany("computers")
                        .HasForeignKey("profileId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("ControleTiAPI.Models.Storage", "storage")
                        .WithMany("computers")
                        .HasForeignKey("storageId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("department");

                    b.Navigation("employee");

                    b.Navigation("processingUnit");

                    b.Navigation("profile");

                    b.Navigation("storage");
                });

            modelBuilder.Entity("ControleTiAPI.Models.ComputerLog", b =>
                {
                    b.HasOne("ControleTiAPI.Models.Computer", "computer")
                        .WithMany("logs")
                        .HasForeignKey("computerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("computer");
                });

            modelBuilder.Entity("ControleTiAPI.Models.ComputerMemory", b =>
                {
                    b.HasOne("ControleTiAPI.Models.Computer", "computer")
                        .WithMany("memories")
                        .HasForeignKey("computerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ControleTiAPI.Models.Memory", "memory")
                        .WithMany("computers")
                        .HasForeignKey("memoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("computer");

                    b.Navigation("memory");
                });

            modelBuilder.Entity("ControleTiAPI.Models.Employee", b =>
                {
                    b.HasOne("ControleTiAPI.Models.Department", "department")
                        .WithMany("employees")
                        .HasForeignKey("departmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("department");
                });

            modelBuilder.Entity("ControleTiAPI.Models.NetworkNode", b =>
                {
                    b.HasOne("ControleTiAPI.Models.Employee", "employeeNetworkNode")
                        .WithMany("networkNodes")
                        .HasForeignKey("employeeId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("ControleTiAPI.Models.Switches", "switchOfNode")
                        .WithMany("networkNodes")
                        .HasForeignKey("switchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("employeeNetworkNode");

                    b.Navigation("switchOfNode");
                });

            modelBuilder.Entity("ControleTiAPI.Models.Preventives.ComputerPreventive", b =>
                {
                    b.HasOne("ControleTiAPI.Models.Computer", "computer")
                        .WithMany("preventives")
                        .HasForeignKey("computerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("computer");
                });

            modelBuilder.Entity("ControleTiAPI.Models.Preventives.DVRPreventive", b =>
                {
                    b.HasOne("ControleTiAPI.Models.DVR", "dvr")
                        .WithMany("preventives")
                        .HasForeignKey("dvrId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("dvr");
                });

            modelBuilder.Entity("ControleTiAPI.Models.Preventives.NobreakPreventive", b =>
                {
                    b.HasOne("ControleTiAPI.Models.Nobreak", "nobreak")
                        .WithMany("preventives")
                        .HasForeignKey("nobreakId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("nobreak");
                });

            modelBuilder.Entity("ControleTiAPI.Models.Preventives.ServerPreventive", b =>
                {
                    b.HasOne("ControleTiAPI.Models.ServerHost", "host")
                        .WithMany("preventives")
                        .HasForeignKey("hostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("host");
                });

            modelBuilder.Entity("ControleTiAPI.Models.Ramal", b =>
                {
                    b.HasOne("ControleTiAPI.Models.Department", "department")
                        .WithMany("ramals")
                        .HasForeignKey("departmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ControleTiAPI.Models.Employee", "employee")
                        .WithMany("ramals")
                        .HasForeignKey("employeeId");

                    b.Navigation("department");

                    b.Navigation("employee");
                });

            modelBuilder.Entity("ControleTiAPI.Models.ServerMemory", b =>
                {
                    b.HasOne("ControleTiAPI.Models.Memory", "memory")
                        .WithMany("servers")
                        .HasForeignKey("memoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ControleTiAPI.Models.ServerHost", "host")
                        .WithMany("memories")
                        .HasForeignKey("serverHostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("host");

                    b.Navigation("memory");
                });

            modelBuilder.Entity("ControleTiAPI.Models.ServerStorage", b =>
                {
                    b.HasOne("ControleTiAPI.Models.ServerHost", "host")
                        .WithMany("storages")
                        .HasForeignKey("serverHostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ControleTiAPI.Models.Storage", "storage")
                        .WithMany("servers")
                        .HasForeignKey("storageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("host");

                    b.Navigation("storage");
                });

            modelBuilder.Entity("ControleTiAPI.Models.ServerVM", b =>
                {
                    b.HasOne("ControleTiAPI.Models.ServerHost", "host")
                        .WithMany("virtualMachines")
                        .HasForeignKey("serverHostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("host");
                });

            modelBuilder.Entity("ControleTiAPI.Models.SkypeEmployee", b =>
                {
                    b.HasOne("ControleTiAPI.Models.Employee", "employee")
                        .WithOne("skype")
                        .HasForeignKey("ControleTiAPI.Models.SkypeEmployee", "employeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("employee");
                });

            modelBuilder.Entity("ControleTiAPI.Models.UserClaims", b =>
                {
                    b.HasOne("ControleTiAPI.Models.User", "user")
                        .WithMany("userClaims")
                        .HasForeignKey("userId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("user");
                });

            modelBuilder.Entity("ControleTiAPI.Models.VpnEmployee", b =>
                {
                    b.HasOne("ControleTiAPI.Models.Employee", "employee")
                        .WithOne("vpn")
                        .HasForeignKey("ControleTiAPI.Models.VpnEmployee", "employeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("employee");
                });

            modelBuilder.Entity("ServerFunctionalityServerHost", b =>
                {
                    b.HasOne("ControleTiAPI.Models.ServerFunctionality", null)
                        .WithMany()
                        .HasForeignKey("functionalitiesid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ControleTiAPI.Models.ServerHost", null)
                        .WithMany()
                        .HasForeignKey("hostsid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ServerFunctionalityServerVM", b =>
                {
                    b.HasOne("ControleTiAPI.Models.ServerFunctionality", null)
                        .WithMany()
                        .HasForeignKey("functionalitiesid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ControleTiAPI.Models.ServerVM", null)
                        .WithMany()
                        .HasForeignKey("virtualMachinesid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ControleTiAPI.Models.CellPhone", b =>
                {
                    b.Navigation("chips");
                });

            modelBuilder.Entity("ControleTiAPI.Models.Computer", b =>
                {
                    b.Navigation("logs");

                    b.Navigation("memories");

                    b.Navigation("preventives");
                });

            modelBuilder.Entity("ControleTiAPI.Models.ComputerProfile", b =>
                {
                    b.Navigation("computers");
                });

            modelBuilder.Entity("ControleTiAPI.Models.DVR", b =>
                {
                    b.Navigation("preventives");
                });

            modelBuilder.Entity("ControleTiAPI.Models.Department", b =>
                {
                    b.Navigation("chips");

                    b.Navigation("computers");

                    b.Navigation("employees");

                    b.Navigation("ramals");
                });

            modelBuilder.Entity("ControleTiAPI.Models.Employee", b =>
                {
                    b.Navigation("chips");

                    b.Navigation("computers");

                    b.Navigation("networkNodes");

                    b.Navigation("ramals");

                    b.Navigation("skype");

                    b.Navigation("vpn");
                });

            modelBuilder.Entity("ControleTiAPI.Models.Memory", b =>
                {
                    b.Navigation("computers");

                    b.Navigation("servers");
                });

            modelBuilder.Entity("ControleTiAPI.Models.Nobreak", b =>
                {
                    b.Navigation("preventives");
                });

            modelBuilder.Entity("ControleTiAPI.Models.ProcessingUnit", b =>
                {
                    b.Navigation("computers");
                });

            modelBuilder.Entity("ControleTiAPI.Models.ServerHost", b =>
                {
                    b.Navigation("memories");

                    b.Navigation("preventives");

                    b.Navigation("storages");

                    b.Navigation("virtualMachines");
                });

            modelBuilder.Entity("ControleTiAPI.Models.Storage", b =>
                {
                    b.Navigation("computers");

                    b.Navigation("servers");
                });

            modelBuilder.Entity("ControleTiAPI.Models.Switches", b =>
                {
                    b.Navigation("networkNodes");
                });

            modelBuilder.Entity("ControleTiAPI.Models.User", b =>
                {
                    b.Navigation("userClaims");
                });
#pragma warning restore 612, 618
        }
    }
}
